org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
appVersion=1.0.1-SNAPSHOT
javaVersion=25
benmanesVersion=0.61.0
errorproneVersion=2.50.0
errorpronePluginVersion=5.1.0
nullawayVersion=0.13.8
nullawayPluginVersion=3.1.0
spotbugsPluginVersion=6.5.10
sonarqubePluginVersion=7.4.0.8496
springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
springdocVersion=3.1.0
gitPropertiesPluginVersion=2.5.7
jacocoVersion=0.8.15
openrewritePluginVersion=7.38.0
rewriteRecipeBomVersion=3.36.0
