org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
appVersion=1.0.1-SNAPSHOT
javaVersion=25
benmanesVersion=0.61.0
errorproneVersion=2.50.0
errorpronePluginVersion=5.1.1
nullawayVersion=0.14.0
nullawayPluginVersion=3.2.0
spotbugsPluginVersion=6.5.11
sonarqubePluginVersion=7.4.0.8496
springBootVersion=4.1.1
springDependencyManagementVersion=1.1.7
springdocVersion=3.1.0
gitPropertiesPluginVersion=4.0.1
jacocoVersion=0.8.15
openrewritePluginVersion=7.39.0
rewriteRecipeBomVersion=3.37.0
