org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
appVersion=1.0.1-SNAPSHOT
javaVersion=25
benmanesVersion=0.54.0
errorproneVersion=2.50.0
errorpronePluginVersion=5.1.0
nullawayVersion=0.13.7
nullawayPluginVersion=3.1.0
spotbugsPluginVersion=6.5.8
sonarqubePluginVersion=7.3.1.8318
springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
springdocVersion=3.0.3
gitPropertiesPluginVersion=2.5.7
openrewritePluginVersion=7.35.0
rewriteRecipeBomVersion=3.33.0
